# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aljacque <aljacque@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 14:01:49 by aljacque          #+#    #+#              #
#    Updated: 2018/11/06 16:07:31 by aljacque         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =  ft_display_file
CC = gcc
CFLAGS = -Wall -Wextra -Werror

all:
	$(CC) $(CFLAGS) -o $(NAME) *.c

clean:
	rm -rf *.o

fclean: clean
	rm -rf $(NAME)
